---
title: '20200418'
author: "YTP"
date: "2020/4/19"
output: html_document
---

```{r}
library(jsonlite)
fromJSON("https://www.dropbox.com/s/6252gbdnv9owljm/dance.json?dl=1", simplifyDataFrame = F) -> dance
```

```{r}
# 前三筆演出的名稱
dance[[1]]$title
dance[[2]]$title
dance[[3]]$title 
```

```{r}
library(purrr)
map(dance,~.x$title) -> dance_title
```

```{r}
dance[[1]]$showInfo
length(dance[[1]]$showInfo)

dance[[2]]$showInfo
length(dance[[1]]$showInfo)
```

```{r}
map(dance,~length(.x$showInfo)) -> dance_showInfoLength
```

```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    )
  )

str(list1)
```

```{r}
# 更改日期
list1[[1]]$birthday <- ymd("1997-03-21")

# 新增資料
list1[[2]] <- list(
  name="Mary",
  birthday=ymd("1998-08-24")
)

str(list1)
```

```{r}
list1[[2]]$status <- c(height=163, weight=45)
list1[[1]]$status[["height"]] <- 176
str(list1)
```

```{r}
list1[[1]][["age"]] <- 21
list1[[2]]["age"] <- list(21)

# 改變「一個」時，使用[[ ]]比較不會錯。
str(list1)
```

```{r}
list1[[1]][c("bloodType","registered")] <- list("AB",TRUE)

str(list1)
```

```{r}
str(list1)
list1[[2]][c(1,2)] <- NULL
str(list1)
```

