---
title: '20200411'
author: "YTP"
date: "2020/4/11"
output: html_document
---

```{r}
library(jsonlite)
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```

```{r}
listExample[["student"]]
listExample$student

listExample[["學期"]] # 小心不是反頓點喔。
listExample$`學期`
```

```{r}
listExample[[1]]
listExample[[2]]
```

```{r}
fromJSON("http://data.ntpc.gov.tw/api/v1/rest/datastore/382000000A-000157-002",
         simplifyDataFrame = F) -> newTaipeiCityVaccine
```

```{r}
newTaipeiCityVaccine$result
```

```{r}
vectorExample <- c("小明","小英","大雄")

# 有多少位置可選：
length(vectorExample)
```

```{r}
vectorExample
vectorExample[c(1,3)]
vectorExample[c(3,2,1)] # 產生重新排列效果
```

```{r}
# 顯示到第一層
str(listExample, max.level=1)

listExample[c(1,2)]
```

```{r}
# 顯示到第一層
#str(listExample, max.level=1)
#listExample[c("學期")]
listExample[c("student","學期","108-2")]
```

```{r}
vectorExample
vectorExample[c(T,T,F)] # 要，要，不要


str(listExample[c(F,T)]) # 不要，要
str(listExample[c(T,T)]) # 要，要
```

```{r}
fromJSON("https://www.dropbox.com/s/qnm9bnz7vccrvcz/taipeiNightMarkets.json?dl=1", simplifyDataFrame = F) -> taipeiNightMarkets
```
   
```{r}
str(taipeiNightMarkets[c(T,F,F,F,T,F,F,F,F,T,F,F,F,T)], max.level = 1)
```

```{r}

###另一種篩選法

selectedMarket <- rep(F, 14)
selectedMarket

selectedMarket[c(1, 5, 10, 14)] <- T
selectedMarket

str(taipeiNightMarkets[selectedMarket], max.level = 1)
```

```{r}
select1 <- numVector[c(T,T,F,T,F,F,T)]; select1
select2 <- select1[c(1,4)]; select2

# 相當於
numVector[c(T,T,F,T,F,F,T)][c(1,4)] ###在numVector 做前後兩次篩選
```

```{r}
today = list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))
tomorrow = list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))

weather = list(today,tomorrow)

print(weather)
str(weather)
```

```{r}
weather[[1]][[2]][[2]] # 今天/新北市/highest_temp
weather[[2]][[2]][[2]] # 明天/新北市/highest_temp
weather[[1]][[2]]
```

```{r}

#修改為純list 無 array

today = list(
  list("台北市",highest_temp = 25,lowest_temp = 18),
  list("新北市",highest_temp = 24,lowest_temp = 15))
tomorrow = list(
  list("台北市",highest_temp = 25,lowest_temp = 18),
  list("新北市",highest_temp = 24,lowest_temp = 15))

weather = list(today,tomorrow)
```

```{r}
weather[[1]][[2]]$highest_temp # 今天/新北市/highest_temp
weather[[2]][[2]]$highest_temp # 明天/新北市/highest_temp
```

```{r}
str(listExample[c(F,T)]) # 不要，要
str(listExample[c(T,T)]) # 要，要

```

```{r}
get1 <- listExample[["學期"]]
get2 <- listExample["學期"]

get1 # 學期拿出來，有3個元素的list
str(get1)
```

```{r}
get2 # listExample 只留下 學期元素，是個只有一個元素的list
str(get2)
```

