---
title: '20200406'
author: "YTP"
date: "2020/4/6"
output: html_document
---

```{r}
library(lubridate)
```

```{r}
tpeTime <- ymd_hms("2020-03-18 13:52:40",
        tz="Asia/Taipei")
```

```{r}
browseURL("https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645")
```

```{r}
class(tpeTime)
typeof(tpeTime)

as.numeric(tpeTime)
```

```{r}
vectorEX <- c(2, 3, 7)
listEX   <- list(2, 3, 7)

print(vectorEX)
print(listEX)
```

```{r}
# list含兩個vectors
`小明108學年課表A` <- list
(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
print(`小明108學年課表A`)
```

```{r}
# list含兩個lists
`小明108學年課表B` <- list(
  list("108-1","高級會計學","高等統計學"),
  list("108-2","食在拉丁美洲")
)
print(`小明108學年課表B`)
```

```{r}
# list含兩個lists, 子層list又各含兩個vectors
`小明108學年課表C` <- list(
  list(
    c("108-1"), # 可只寫 "108-1"
    c("高級會計學","高等統計學")
  ),
  list(
    c("108-2"),
    c("食在拉丁美洲")
  )
)
print(`小明108學年課表C`)
```

```{r}
library(lubridate)
#個別
authorValues <- 
  list(
    name="Martin老師",  
    email="mtlin@gm.ntpu.edu.tw",
    time=ymd_hms("2020-03-25T07:17:40Z")
  )
committerValues <- 
  list(
    name="emilyluckey", 
    email="emily007@gmail.com",
    time=ymd_hms("2020-03-26T08:18:40Z")
  )
# 統整
commit <- list(
  author=authorValues,
  commmitter=committerValues,
  message="update"
)

print(commit)
```

```{r}
library(jsonlite) # 不少同學這行會有Error，還記得如何排除嗎？
toJSON(commit)
```

```{r}
#學期內容
all_108 = list(
  first_108 = list(
    course_1 = list(
      Name = "個體經濟學",
      Teacher = "Alice",
      Grade = 85
    ),
    course_2 = list(
      Name = "總體經濟學",
      Teacher = "Mark",
      Grade = 78
    )
  ), 
  second_108 = list(
    course_1 =list(
      Name = "作業研究",
      Teacher = "Jason",
      Grade = 90
    )
  )
)
#個人標頭
`小明的修課記錄` = 
  list(
    name = "小明",
    semesters = all_108 
  )

print(`小明的修課記錄`)
```

```{r}
library(jsonlite)
fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
```

```{r}
load("threeObjects.Rda")
```

```{r}
save(commit, `小明的修課記錄`, file = "20200406.Rda")
```

