---
title: '20200609'
author: "YTP"
date: "2020/6/9"
output: html_document
---

```{r}
# p=1.2的需求量
p=1.2
qd <- 10-5*p # 小心是5*p, 不能寫5p
# p=1.3的需求量
p=1.3
qd <- 10-5*p
# p=1.4的需求量
p=1.4
qd <- 10-5*p
```

```{r}
demand <- # 創造一個物件叫demand
  function(p){ # 定義這個物件為函數
    q_d <- 10-5*p # 小心是5*p, 不能寫5p
  }
```

```{r}
# p=1.2的需求量
demand(1.2) 
# p=1.3的需求量
demand(1.3)
# p=1.4的需求量
demand(1.4)
```

```{r}
demand_return <- 
  function(p){
    q_d <- 10-5*p
```


```{r}
return(q_d)
  }
# 印在螢幕，但Global Environment並不會有q_d
demand_return(1.2)
```
#上次運算的暫存值
```{r}
.Last.value
```

```{r}
demand_return(1.2) # 相當於
4
```

```{r}
demand_return(1.2) -> q_d1.2 # 相當於
4 -> q_d1.2
```

```{r}
askSilly_weather <- function(locationInput,dateInput){
  jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
  
  (weather_next36hours$cwbopendata$dataset$location$locationName == locationInput) -> pick_location
  
  weather_next36hours$cwbopendata$dataset$location$weatherElement[pick_location][[1]] -> weatherAtLocation
  (weatherAtLocation$elementName=="MaxT") ->
    pick_MaxT
  (weatherAtLocation$elementName=="MinT") ->
    pick_MinT
  weatherAtLocation$time[pick_MaxT][[1]]$parameter$parameterName[[1]] -> maxT
  weatherAtLocation$time[pick_MinT][[1]]$parameter$parameterName[[1]] -> minT
  
  glue::glue("{locationInput} {dateInput} 氣溫，最高{maxT}度，最低{minT}度。")
}
```

```{r}
askSilly_weather("臺中市",today())
askSilly_weather("花蓮縣",today())
```

```{r}
class(demand_return)
# 查詢函數formals arguments要求

# 查詢函數主體
body(askSilly_weather)
```
#函數可以存在list裡
```{r}
learning_topics <- 
  list(
    subject="函數",
    date=lubridate::ymd("2020-06-03"),
    functionsCreated=list(
      demand=demand_return # 等號右邊是呼叫demand_return的定義值，也就是function(...){...}值定義本身。
    )
  )
```

```{r}
learning_topics$functionsCreated$demand(1.2)
```
#function本身的運作並不能只靠它的定義值function(...){...}，還要有適當的環境（environment）條件才能生存。若物件的生存運作需要有適當的環境，表示電腦要存這個物件時還需要包含（enclose）它的（生存）環境一起存。這種儲存型態叫closure（閉包）。
```{r}
typeof(demand_return)
```

```{r}
# 查詢函數執行所要求環境
environment(demand_return)
```

```{r}
# 若函數執行需要Global environment已存在某些物件，查詢需要哪些物件
codetools::findGlobals(demand_return)
```

```{r}
intercept <- 10
slope <- -5
myDemand <- function(p){
  q_d <- intercept + slope*p
  return(q_d)
}
```

```{r}
environment(demand_return)
environment(myDemand)
```

```{r}
codetools::findGlobals(demand_return)
codetools::findGlobals(myDemand) 

# myDemand對Global environment的要求多了intercept及slope
```

```{r}
# 移除global environment裡的intercept及slope
rm(intercept, slope)
```

```{r}
myDemand(1.2) # 無法運作
# myDemand的運作需要global environment裡的intercept, slope物件
```
## global environment裡的intercept, slope值若有改變，它的運作結果也會不同。(這種「要運作才去呼叫值」的特性叫Lazy evaluation，惰性求值)
```{r}
intercept <- 10
slope <- -5
myDemand(1.2)
```

```{r}
slope <- -1
myDemand(1.2)
```

```{r}
intercept <- 5
slope <- -1.2
myDemand(1.2)
```

```{r}
## 為lazy evaluation 設定預設值，將原本在global environment的變數設定到function內，給預設值

myDemand2 <- function(p, intercept=10, slope=-5){
  q_d <- intercept + slope*p
  return(q_d)
}
```

```{r}
environment(myDemand2)
codetools::findGlobals(myDemand2) # 不依靠global env裡的intercept/slope
```

```{r}
myDemand2(1.2)
myDemand2(1.2, slope=-1)
myDemand2(1.2, intercept=5, slope=-1.2)
```

