---
title: '20200325'
author: "YTP"
date: "2020/3/25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
num1 <- c(1)
num2 <- c(2)
```


```{r}
num3 <- c(num1,num2)
num4 <- c(num2,num4)
```

```{r}
char1<-"你好"
char2<-'你好'
```

```{r}
char1Vector<-c("你好","How are you?")
```

```{r}
typeof(char1Vector)
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep = "\n")
```

```{r}
library(httr)
library(dplyr)
GET("https://api.github.com/repos/tpemartin/108-2-56-inclass-practice/commits") %>%
  content() %>%
  View()
```

```{r}
num <- c(1.5, 2, 3)
int <- c(1L, 3L, -2L)
char <- c("1.5","2","3")
logi <- c(T,T,F)

typeof(num)
typeof(int)
typeof(char)
typeof(logi)
```

```{r}
class(num)
class(int)
class(char)
class(logi)
```

```{r}
library(httr)
library(dplyr)
GET("https://api.github.com/repos/tpemartin/108-2-56-inclass-practice/commits") %>%
  content() %>%
  View()
```

```{r}
library(googlesheets4)
`出席狀況表單網址` <-"https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645"  # 缺乏定義值
ss <- as_sheets_id(`出席狀況表單網址`)
homework_sheet <- read_sheet(ss,sheet=1)
```

