---
title: '20200523'
author: "YTP"
date: "2020/5/23"
output: html_document
---

```{r}
library(purrr)
```

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```

```{r}
#取出所有屬性中，小新的資料
pick_小新 <- example$name == "小新"
data_selected <- 
  list(
    name=example$name[pick_小新],
    weight=example$weight[pick_小新],
    height=example$height[pick_小新],
    hobby=example$hobby[pick_小新],
    residence=example$residence[pick_小新],
    allowance=example$allowance[pick_小新],
    bloodType=example$bloodType[pick_小新]
  )
```

purrr底下的map()允許我們

使用".x"來代表每個元素操作，即[[1]], [[2]], ..., [[7]]
所以

對每個元素進行[pick_小新]

可以寫成.x[pick_小新]。

由於.x[pick_小新]是個公式化的動作，在R，~代表要形成一個公式(formula)

```{r}
#相當於
map(example, ~.x[pick_小新]) -> 
  data_selected 
  
data_selected
```

```{r}
jsonlite::fromJSON("https://www.dropbox.com/s/6252gbdnv9owljm/dance.json?dl=1", simplifyDataFrame = F) -> dance
```

```{r}
# 第一個dance表演名稱
dance[[1]]$title
# 第二個dance表演名稱
dance[[2]]$title
```

```{r}
#相當於
map(dance, ~.x$title) ->
  list_titles

```

```{r}
# 記載第一個表演的所有場次訊息
dance[[1]]$showInfo
str(dance[[1]]$showInfo)
# 計算第一個表演有幾個場次
length(dance[[1]]$showInfo)
# 計算第二個表演有幾個場次
length(dance[[2]]$showInfo)
```

```{r}
#第4個表演有多個場次，想知道它們所有的日期時間
str(dance[[4]]$showInfo)
map(dance[[4]]$showInfo, ~ .x$time) ->
list_showTimes_dance4
list_showTimes_dance4
```
##以下練習
```{r}
jsonlite::fromJSON("https://data.ntpc.gov.tw/api/datasets/0EE4E6BF-CEE6-4EC8-8FE1-71F544015127/json/preview", simplifyDataFrame = F) -> busRoutes
```

```{r}
test1 = list(
  Id = map(busRoutes, ~ .x[[1]]),
  providerId = map(busRoutes, ~ .x[[2]]),
  providerName = map(busRoutes, ~ .x[[3]]),
  nameZh = map(busRoutes, ~ .x[[4]])
)
test1$providerName[test1$Id == "16978"]
```

```{r}
jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
```

```{r}
threeHeigths <- c(Gary=178, John=182, Cam=175)
```

```{r}
##一般寫法
# 先排序由大到小，
sort(threeHeigths, decreasing=T) -> sorted_heights

# 把排好的人名取出
names(sorted_heights) -> sorted_persons

# 接著取出第一個位置的人名
sorted_persons[[1]] -> highestPerson
```

```{r}
#或者
names(sort(threeHeigths, decreasing = T))[[1]] -> highestPerson
```

```{r}
library(magrittr)
library(stringr)
```

```{r}
#使用pipe
sort(threeHeigths, decreasing=T) %>% 
names(.) %>%
.[[1]] -> highestPerson
```

```{r}
##以下三者意思相同
f(w) -> x
g(x) -> y
h(y) -> z

f(w) %>%
  g(.) %>% 
  h(.) -> z

w %>%
  f(.) %>%
  g(.) %>%
  h(.) -> z
```

```{r}
# 由cities創出每個元素對應的北部、東部、中部region factor
cities <- factor(c("台北","花蓮","台東","台中"))
levels(cities)
```

```{r}
region <- cities

# 以下為一般寫法
levels(region) -> currentLevels
str_replace(currentLevels,"台北","北部") -> currentLevels1
str_replace(currentLevels1,"花蓮|台東","東部") -> currentLevels2
str_replace(currentLevels2,"台中","中部") -> regionLevels
regionLevels -> levels(region)
```

```{r}
#以下為改用pipe寫法
levels(region) %>% 
  str_replace(.,"台北","北部") %>%
  str_replace(.,"花蓮|台東","東部") %>%
  str_replace(.,"台中","中部") ->
  levels(region)
```

```{r}
num <- c(2,97,22,15,7)

# 選出大於50的數字
(num > 50) -> pick_big
num[pick_big]
```

```{r}
#相當於
(num > 50) %>%
  num[.]
```

若代表中間物件的"."在函數的"第一位"則.*可省略不寫，連它後面的","也去掉
```{r}
levels(region) %>%
  str_replace(.,"台北","北部") %>%
  str_replace(.,"花蓮|台東","東部") %>%
  str_replace(.,"台中","中部") ->
  levels(region)
```

```{r}
#可再簡化成
levels(region) %>% 
  str_replace("台北","北部") %>%
  str_replace("花蓮|台東","東部") %>%
  str_replace("台中","中部") -> 
  levels(region)
```

要注意pipe只能丟到最外層函數，以下
```{r}
# 資料
population <- c(`cityA`=500,`cityB`=1500, `cityC`=399)
cities <- c("cityA","cityA","cityB","cityB","cityC")

# 分析步驟
names(sort(population)) -> setLevels
factor(cities, levels = setLevels) -> cities 
```

不能寫成
```{r}
population %>% 
  names(sort(.)) %>%
  factor(cities, levels=.) -> cities
```

會變成丟給names，不用{}下，要寫成
```{r}
population %>%
  sort() %>%
  names() %>%
  factor(cities, levels=.) -> cities
```


若遇到pipe 串接的下一段並不是單純的函數的話，可以用"{}"把此段內容括起來並把前一段output要放的位置換成"."。
```{r}
dataList <- list(
  num=c(2,97,22,15,7),
  chr=c("2","97","22","15","7")
)
```

```{r}
#dataList中元素class為numeric裡那些大於50的數字
map(dataList, is.numeric) -> results
unlist(results) -> pick_numeric

dataList[pick_numeric] -> num_element
(num_element[[1]] > 50) -> pick_big
num_element[[1]][pick_big] -> bigNumber
```

```{r}
#相當於
map(dataList, is.numeric) %>%
unlist(.) %>%

dataList[.] %>%
{(.[[1]] > 50)} %>%
num_element[[1]][.] -> bigNumber
```

錯誤
```{r}
population %>% 
  names(sort(.)) %>%
  factor(cities, levels=.) -> cities
```
要改成
```{r}
population %>% 
  {names(sort(.))} %>%
  factor(cities, levels=.) -> cities
```

#以下練習
```{r}
jsonlite::fromJSON("https://od.cdc.gov.tw/eic/Day_Confirmation_Age_County_Gender_19CoV.json") -> covid19

jsonlite::fromJSON(
  "https://www.dropbox.com/s/jckqryeh5zeat5w/regionPopulation.json?dl=1"
) -> population
unlist(population) -> population
```

#基於以下原始寫法改寫
```{r}
covid19$縣市 <- factor(covid19$縣市)

levels(covid19$縣市) -> levelsInData
population[levelsInData] -> population

population <- sort(population, decreasing=T)
population

newLevels <- names(population)
newLevels

covid19$縣市 <-
  factor(
    covid19$縣市, levels=newLevels
  )

levels(covid19$縣市)
```

```{r}
#?
covid19$縣市 = factor(covid19$縣市)

  levels(covid19$縣市) %>% population[.] ->population
  population %>%
  sort(., decreasing = T) %>% names() %>%
  {factor(covid19$縣市, levels = .)}
levels(covid19$縣市)
```

